add_subdirectory(host_os_board)
add_subdirectory(blackpill)
add_subdirectory(bluepill_plus)
add_subdirectory(mini_stm32h7)
add_subdirectory(weact_stm32f446)
add_subdirectory(pico)
add_subdirectory(pico2)
add_subdirectory(pico_hostmode)
add_subdirectory(pico_w)
add_subdirectory(waveshare_rp2350_touch_lcd_1_69)
add_subdirectory(waveshare_rp2350_touch_lcd_2_8)
light_promote_shared_vars()
